const estructuraspesadas = [
  { id: 1, url: "./images/EstructurasPesadas/1.jpg" },
  { id: 2, url: "./images/EstructurasPesadas/2.jpg" },
  { id: 3, url: "./images/EstructurasPesadas/3.jpg" },
  { id: 4, url: "./images/EstructurasPesadas/4.jpg" },
  { id: 5, url: "./images/EstructurasPesadas/5.jpg" },
  { id: 6, url: "./images/EstructurasPesadas/6.jpg" },
  { id: 7, url: "./images/EstructurasPesadas/7.jpg" },
  { id: 8, url: "./images/EstructurasPesadas/8.jpg" },
  { id: 9, url: "./images/EstructurasPesadas/9.jpg" },
  { id: 10, url: "./images/EstructurasPesadas/10.jpg" },
  { id: 11, url: "./images/EstructurasPesadas/11.jpg" },
  { id: 12, url: "./images/EstructurasPesadas/12.jpg" },
  { id: 13, url: "./images/EstructurasPesadas/13.jpeg" },
  { id: 14, url: "./images/EstructurasPesadas/14.jpeg" },
  { id: 15, url: "./images/EstructurasPesadas/15.jpeg" },
  { id: 16, url: "./images/EstructurasPesadas/16.jpeg" },
  { id: 17, url: "./images/EstructurasPesadas/17.jpeg" },
  { id: 18, url: "./images/EstructurasPesadas/18.jpeg" },
  { id: 19, url: "./images/EstructurasPesadas/19.jpeg" },
  { id: 20, url: "./images/EstructurasPesadas/20.jpeg" },
  { id: 21, url: "./images/EstructurasPesadas/21.jpeg" },
  { id: 22, url: "./images/EstructurasPesadas/22.jpeg" },
  { id: 23, url: "./images/EstructurasPesadas/23.jpeg" },
  { id: 24, url: "./images/EstructurasPesadas/24.jpeg" },
  { id: 25, url: "./images/EstructurasPesadas/25.jpeg" },
  { id: 26, url: "./images/EstructurasPesadas/26.jpeg" },
  { id: 27, url: "./images/EstructurasPesadas/27.jpeg" },
  { id: 28, url: "./images/EstructurasPesadas/28.jpeg" },
  { id: 29, url: "./images/EstructurasPesadas/29.jpeg" },
  { id: 30, url: "./images/EstructurasPesadas/30.jpeg" },
  { id: 31, url: "./images/EstructurasPesadas/31.jpeg" },
  { id: 32, url: "./images/EstructurasPesadas/32.jpeg" },
  { id: 33, url: "./images/EstructurasPesadas/33.jpeg" },
  { id: 34, url: "./images/EstructurasPesadas/34.jpeg" },
  { id: 35, url: "./images/EstructurasPesadas/35.jpeg" },
  { id: 36, url: "./images/EstructurasPesadas/36.jpeg" },
];

export default estructuraspesadas;
