const maquinasyequipos = [
  { id: 1, url: "./images/MaquinasYEquipos/1.jpg" },
  { id: 2, url: "./images/MaquinasYEquipos/2.jpg" },
  { id: 3, url: "./images/MaquinasYEquipos/3.jpg" },
  { id: 4, url: "./images/MaquinasYEquipos/4.jpg" },
  { id: 5, url: "./images/MaquinasYEquipos/5.jpg" },
  { id: 6, url: "./images/MaquinasYEquipos/6.jpg" },
  { id: 7, url: "./images/MaquinasYEquipos/7.jpg" },
  { id: 8, url: "./images/MaquinasYEquipos/8.jpg" },
  { id: 9, url: "./images/MaquinasYEquipos/9.jpg" },
  { id: 10, url: "./images/MaquinasYEquipos/10.jpg" },
  { id: 11, url: "./images/MaquinasYEquipos/11.jpg" },
  { id: 12, url: "./images/MaquinasYEquipos/12.jpg" },
  { id: 13, url: "./images/MaquinasYEquipos/13.jpg" },
  { id: 14, url: "./images/MaquinasYEquipos/14.jpg" },
  { id: 15, url: "./images/MaquinasYEquipos/15.jpg" },
  { id: 16, url: "./images/MaquinasYEquipos/16.jpg" },
  { id: 17, url: "./images/MaquinasYEquipos/17.jpg" },
  { id: 18, url: "./images/MaquinasYEquipos/18.jpg" },
  { id: 19, url: "./images/MaquinasYEquipos/19.jpeg" },
  { id: 20, url: "./images/MaquinasYEquipos/20.jpeg" },
  { id: 21, url: "./images/MaquinasYEquipos/21.jpeg" },
  { id: 22, url: "./images/MaquinasYEquipos/22.jpeg" },
];

export default maquinasyequipos;
