const tanque = [
  { id: 1, url: "./images/Tanque/12.jpg" },
  { id: 2, url: "./images/Tanque/13.jpg" },
  { id: 3, url: "./images/Tanque/14.jpg" },
  { id: 4, url: "./images/Tanque/15.jpg" },
  { id: 5, url: "./images/Tanque/16.jpg" },
  { id: 6, url: "./images/Tanque/17.jpg" },
  { id: 7, url: "./images/Tanque/18.jpg" },
  { id: 8, url: "./images/Tanque/19.jpg" },
  { id: 9, url: "./images/Tanque/20.jpg" },
  { id: 10, url: "./images/Tanque/21.jpg" },
  { id: 11, url: "./images/Tanque/22.jpg" },
  { id: 12, url: "./images/Tanque/23.jpg" },
  { id: 13, url: "./images/Tanque/24.jpg" },
  { id: 14, url: "./images/Tanque/25.jpg" },
  { id: 15, url: "./images/Tanque/26.jpg" },
  { id: 16, url: "./images/Tanque/27.jpg" },
  { id: 17, url: "./images/Tanque/28.jpg" },
  { id: 18, url: "./images/Tanque/29.jpg" },
  { id: 19, url: "./images/Tanque/31.jpg" },
  { id: 20, url: "./images/Tanque/32.jpg" },
  { id: 21, url: "./images/Tanque/33.jpg" },
  { id: 22, url: "./images/Tanque/34.jpg" },
  { id: 23, url: "./images/Tanque/35.jpg" },
  { id: 24, url: "./images/Tanque/36.jpg" },
  { id: 25, url: "./images/Tanque/37.jpg" },
  { id: 26, url: "./images/Tanque/666.jpg" },
  { id: 27, url: "./images/Tanque/tanque2.jpeg" },
];

export default tanque;
