const tanquesydepositos = [
  { id: 1, url: "./images/TanquesYDepositos/1.jpg" },
  { id: 2, url: "./images/TanquesYDepositos/2.jpg" },
  { id: 3, url: "./images/TanquesYDepositos/3.jpeg" },
  { id: 4, url: "./images/TanquesYDepositos/4.jpg" },
  { id: 5, url: "./images/TanquesYDepositos/5.jpg" },
  { id: 6, url: "./images/TanquesYDepositos/6.jpg" },
  { id: 7, url: "./images/TanquesYDepositos/7.jpg" },
  { id: 8, url: "./images/TanquesYDepositos/8.jpg" },
  { id: 9, url: "./images/TanquesYDepositos/9.jpg" },
  { id: 10, url: "./images/TanquesYDepositos/10.jpg" },
  { id: 11, url: "./images/TanquesYDepositos/11.jpg" },
  { id: 12, url: "./images/TanquesYDepositos/12.jpg" },
  { id: 13, url: "./images/TanquesYDepositos/13.jpg" },
  { id: 14, url: "./images/TanquesYDepositos/14.jpg" },
  { id: 15, url: "./images/TanquesYDepositos/15.jpg" },
  { id: 16, url: "./images/TanquesYDepositos/16.jpg" },
  { id: 17, url: "./images/TanquesYDepositos/17.jpeg" },
  { id: 18, url: "./images/TanquesYDepositos/18.jpeg" },
  { id: 19, url: "./images/TanquesYDepositos/19.jpeg" },
  { id: 20, url: "./images/TanquesYDepositos/TAN1.png" },
  { id: 21, url: "./images/TanquesYDepositos/TAN2.png" },
  { id: 22, url: "./images/TanquesYDepositos/TAN3.png" },
  { id: 23, url: "./images/TanquesYDepositos/TAN4.png" },
  { id: 24, url: "./images/TanquesYDepositos/TAN5.png" },
  { id: 25, url: "./images/TanquesYDepositos/TAN6.png" },
  { id: 26, url: "./images/TanquesYDepositos/TAN7.png" },
  { id: 27, url: "./images/TanquesYDepositos/TAN8.png" },
  { id: 28, url: "./images/TanquesYDepositos/TAN9.png" },
  { id: 29, url: "./images/TanquesYDepositos/TAN10.png" },
];

export default tanquesydepositos;
